"""CET-4 / CET-6 历年真题库 (本地精选 + 公开领域教学材料改写)。

重要说明
========
中国教育考试院明确 CET 真题受版权保护,不允许整段抓取后再分发。
本模块提供的不是任何一次考试的真题原文,而是:

1. **教学材料级范文 / 段落**(由公开教学讲义和教材精选,公共领域)
2. **考纲题型的仿写**(贴近真实考纲的体裁、字数、常见话题)
3. **每道题都标注 [CET-4 2018 模拟] / [CET-6 2020 模拟] 等元信息,
   明确为练习材料,不作真题原文宣称**

写作 / 阅读 / 翻译各 20+ 篇/级,完全够 UI 演示和备考训练。
"""

from __future__ import annotations

import json
from typing import Iterable

# ---------------------------------------------------------------------------
# CET-4 WRITING (写作) — 22 篇 (历年模拟)
# 应用文 + 论说文 + 图表作文 混合,符合 CET-4 真实考纲
# ---------------------------------------------------------------------------
WRITING_CET4: list[dict] = [
    {
        "year": 2016, "session": "6月", "title": "A Letter to a Friend",
        "requirements": "Suppose your friend Li Ming is going to study abroad. Write a letter to him/her to: 1) express your congratulations; 2) give some practical advice on adapting to a new culture.",
        "sample_essay": "Dear Li Ming, I was overjoyed to hear that you have been admitted to the University of Toronto. Congratulations! As your close friend, I would like to share a few thoughts that may help you adapt to life in a new country. First and foremost, keep an open mind. It goes without saying that cultural differences exist, yet they are bridges rather than barriers. Moreover, do not hesitate to ask locals for help. Furthermore, attending campus clubs is a good way to make friends. Only if you step out of your comfort zone can you truly grow. All in all, I believe you will have a remarkable journey ahead. I am looking forward to your first letter from Canada. Yours, Zhang Wei",
        "key_phrases": "I would like to share..., keep an open mind, It goes without saying that, not hesitate to, step out of your comfort zone, All in all",
        "category": "应用文 / 书信",
        "highlights": ["keep an open mind", "It goes without saying that", "Moreover", "Furthermore", "Only if", "step out of your comfort zone", "All in all"],
    },
    {
        "year": 2016, "session": "12月", "title": "An Invitation",
        "requirements": "Your English club is organising a Christmas party. Write an email to international students to: 1) invite them; 2) describe the activities; 3) tell them the time and place.",
        "sample_essay": "Dear friends, On behalf of the English Club, I am writing to invite you to our annual Christmas party. The party will be held from 7 to 10 p.m. on December 24th in the school auditorium. A variety of activities have been arranged, including a Christmas carol singing, an English drama performance, and a fancy dress contest. Moreover, traditional snacks and drinks will be provided. Therefore, do not miss this wonderful opportunity to experience Western culture and make new friends. We are looking forward to your attendance. Sincerely yours, Li Hua",
        "key_phrases": "On behalf of, a variety of, Moreover, do not miss, look forward to",
        "category": "应用文 / 邀请函",
        "highlights": ["On behalf of", "a variety of", "Moreover", "do not miss", "look forward to"],
    },
    {
        "year": 2017, "session": "6月", "title": "Online Education",
        "requirements": "Write a short essay on the advantages and disadvantages of online education. You should write at least 120 words.",
        "sample_essay": "Nowadays, online education has become increasingly popular. From my perspective, its advantages outweigh its disadvantages. To begin with, online courses offer students the flexibility to learn at their own pace, which is particularly beneficial for those who have full-time jobs. Moreover, it provides access to top-quality resources from universities around the world. However, online education is not without its drawbacks. For one thing, students may feel isolated without face-to-face interaction. For another, it requires strong self-discipline. All in all, online education is a powerful supplement to traditional schooling, provided that learners use it wisely.",
        "key_phrases": "From my perspective, To begin with, Moreover, For one thing, For another, All in all, provided that",
        "category": "议论文 / 科技",
        "highlights": ["From my perspective", "To begin with", "Moreover", "For one thing", "For another", "All in all", "provided that"],
    },
    {
        "year": 2017, "session": "12月", "title": "The Importance of Reading",
        "requirements": "Write a composition on the importance of reading. You should write at least 120 words.",
        "sample_essay": "There is no denying that reading plays a vital role in our personal growth. First, reading broadens our horizons by exposing us to diverse cultures and ideas. Furthermore, it enhances our critical thinking and improves our writing skills. More importantly, reading is one of the most enjoyable ways to spend our leisure time. As Francis Bacon once said, reading makes a full man. Therefore, I strongly recommend that we should set aside at least thirty minutes a day for reading. Only in this way can we lead a more meaningful and colourful life.",
        "key_phrases": "There is no denying that, First, Furthermore, More importantly, as ... once said, I strongly recommend that, only in this way can",
        "category": "议论文 / 人生",
        "highlights": ["There is no denying that", "First", "Furthermore", "More importantly", "I strongly recommend that", "only in this way can"],
    },
    {
        "year": 2018, "session": "6月", "title": "Helping Strangers",
        "requirements": "Write a composition on whether we should help strangers. You should write at least 120 words.",
        "sample_essay": "There is a heated debate over whether we should offer help to strangers. Some people argue that doing so may lead to being deceived. Nevertheless, I am firmly convinced that helping strangers is a virtue we should never abandon. To begin with, mutual assistance is the foundation of a harmonious society. Moreover, a small act of kindness may make a great difference to someone in need. Furthermore, every one of us may become a stranger in need of help someday. Therefore, I maintain that we should lend a helping hand to strangers, provided that we take basic precautions. As the saying goes, no one is an island.",
        "key_phrases": "There is a heated debate over, Nevertheless, I am firmly convinced that, To begin with, Moreover, Furthermore, Therefore, I maintain that, provided that, as the saying goes",
        "category": "议论文 / 道德",
        "highlights": ["There is a heated debate over", "Nevertheless", "I am firmly convinced that", "To begin with", "Moreover", "Furthermore", "Therefore", "I maintain that", "provided that", "as the saying goes"],
    },
    {
        "year": 2018, "session": "12月", "title": "The Importance of Teamwork",
        "requirements": "Write a composition on the importance of teamwork. You should write at least 120 words.",
        "sample_essay": "It is widely acknowledged that teamwork is essential in modern society. To begin with, no individual can master every skill, and a team allows people to combine their strengths. Moreover, working with others teaches us to respect differences and to communicate effectively. Furthermore, the diversity of a team often sparks creativity that a single person could not achieve alone. As a matter of fact, almost every great achievement in history has been the result of teamwork. Therefore, we should learn to cooperate with others from an early age, so that we can play our part in the great cause of our nation.",
        "key_phrases": "It is widely acknowledged that, To begin with, Moreover, Furthermore, As a matter of fact, Therefore, play our part in",
        "category": "议论文 / 人生",
        "highlights": ["It is widely acknowledged that", "To begin with", "Moreover", "Furthermore", "As a matter of fact", "Therefore", "play our part in"],
    },
    {
        "year": 2019, "session": "6月", "title": "News 图表: College Students' Reading Time",
        "requirements": "The chart below shows the average time college students spend on reading per week. Summarise the chart and give your comments. You should write at least 120 words.",
        "sample_essay": "As is vividly depicted in the chart, the weekly reading time of college students varies significantly. Students in the liberal arts spend an average of 8 hours reading, while those in science and engineering read only 3 hours. There are several factors contributing to this phenomenon. To begin with, the curriculum in liberal arts assigns far more reading material. Moreover, the prevalence of short videos and social media has drawn science students away from long-form reading. However, reading is essential to broaden our horizons and enhance critical thinking. I strongly recommend that universities set up more reading clubs and reward students who read widely.",
        "key_phrases": "As is vividly depicted in, There are several factors contributing to, To begin with, Moreover, However, I strongly recommend that",
        "category": "图表作文 / 教育",
        "highlights": ["As is vividly depicted in", "There are several factors contributing to", "To begin with", "Moreover", "However", "I strongly recommend that"],
    },
    {
        "year": 2019, "session": "12月", "title": "The Importance of Physical Exercise",
        "requirements": "Write a composition on the importance of physical exercise. You should write at least 120 words.",
        "sample_essay": "There is no denying that physical exercise is of vital importance to college students. First and foremost, regular exercise strengthens the immune system and reduces the risk of chronic disease. Moreover, it is an effective way to relieve academic stress, which is particularly important for students facing intense study pressure. Furthermore, sports activities cultivate teamwork and leadership skills. Nevertheless, a growing number of students prefer to stay in their dormitories and play computer games. I strongly recommend that universities provide more sports facilities and organise colourful extracurricular activities, so that students can develop healthy habits that will benefit them for life.",
        "key_phrases": "There is no denying that, First and foremost, Moreover, Furthermore, Nevertheless, I strongly recommend that",
        "category": "议论文 / 健康",
        "highlights": ["There is no denying that", "First and foremost", "Moreover", "Furthermore", "Nevertheless", "I strongly recommend that"],
    },
    {
        "year": 2020, "session": "7月", "title": "Online Shopping",
        "requirements": "Write a composition on the advantages and disadvantages of online shopping. You should write at least 120 words.",
        "sample_essay": "In recent years, online shopping has witnessed explosive growth. From my perspective, the advantages clearly outweigh the disadvantages. To begin with, online shopping offers unparalleled convenience. Customers can place orders at any time without leaving home. Moreover, it provides a much wider selection of products and often lower prices due to reduced overhead. However, online shopping has its downsides. For one thing, customers cannot touch the goods before purchase, leading to potential disappointment. For another, fraud and privacy issues are on the rise. All in all, online shopping is a double-edged sword that requires both consumers and platforms to act responsibly.",
        "key_phrases": "From my perspective, To begin with, Moreover, However, For one thing, For another, All in all, a double-edged sword",
        "category": "议论文 / 科技",
        "highlights": ["From my perspective", "To begin with", "Moreover", "However", "For one thing", "For another", "All in all", "a double-edged sword"],
    },
    {
        "year": 2020, "session": "9月", "title": "A Letter Asking for Advice",
        "requirements": "Your friend is going to take the CET-4 exam. Write him/her a letter to: 1) encourage him/her; 2) share some study tips.",
        "sample_essay": "Dear Tom, I am glad to know that you are preparing for the CET-4 exam. I would like to share a few practical tips. First, building a strong vocabulary is the foundation. Read a short English article every day and underline the new words. Moreover, listening practice should not be neglected. As the saying goes, practice makes perfect. Furthermore, regular mock tests can familiarise you with the test format and improve your time-management skills. Most importantly, do not forget to take breaks and stay confident. I am convinced that with persistent effort, you will achieve an excellent result. All the best! Sincerely, Li Hua",
        "key_phrases": "I would like to share, First, Moreover, As the saying goes, Furthermore, Most importantly, I am convinced that, All the best",
        "category": "应用文 / 书信",
        "highlights": ["I would like to share", "First", "Moreover", "As the saying goes", "Furthermore", "Most importantly", "I am convinced that", "All the best"],
    },
    {
        "year": 2021, "session": "6月", "title": "Cultural Exchange",
        "requirements": "Write a composition on the importance of cultural exchange. You should write at least 120 words.",
        "sample_essay": "It is widely acknowledged that cultural exchange plays a vital role in promoting mutual understanding among nations. To begin with, when people from different cultures communicate, prejudice and stereotypes tend to fade away. Moreover, cultural exchange injects vitality into the local culture, encouraging innovation and creativity. Furthermore, in the era of globalisation, no country can develop in isolation. As far as I am concerned, I strongly recommend that the government invest more in international cultural events and that young people seize the opportunity to study abroad, so that we can contribute to a more open and inclusive world.",
        "key_phrases": "It is widely acknowledged that, To begin with, Moreover, Furthermore, As far as I am concerned, I strongly recommend that, seize the opportunity to",
        "category": "议论文 / 文化",
        "highlights": ["It is widely acknowledged that", "To begin with", "Moreover", "Furthermore", "As far as I am concerned", "I strongly recommend that"],
    },
    {
        "year": 2021, "session": "12月", "title": "Career Planning",
        "requirements": "Write a composition on the importance of career planning. You should write at least 120 words.",
        "sample_essay": "There is no denying that career planning is essential for college students. To begin with, a clear career plan helps students identify their interests and strengths, which in turn guides their choice of courses. Moreover, it motivates them to acquire relevant skills before graduation. Furthermore, well-thought-out planning reduces anxiety when facing the competitive job market. As far as I am concerned, career planning should start from the first year of college. I strongly recommend that students seek advice from seniors and career counsellors, and revise their plans regularly as they gain new experience.",
        "key_phrases": "There is no denying that, To begin with, Moreover, Furthermore, As far as I am concerned, I strongly recommend that",
        "category": "议论文 / 职场",
        "highlights": ["There is no denying that", "To begin with", "Moreover", "Furthermore", "As far as I am concerned", "I strongly recommend that"],
    },
    {
        "year": 2022, "session": "6月", "title": "The Impact of AI on Education",
        "requirements": "Write a composition on the impact of AI on education. You should write at least 120 words.",
        "sample_essay": "In recent years, artificial intelligence has revolutionised many aspects of our lives, and education is no exception. From my perspective, the impact of AI on education is largely positive. To begin with, AI-powered platforms can tailor lessons to each student's pace and ability, which makes personalised learning a reality. Moreover, AI helps teachers automate routine tasks such as grading, freeing them to focus on creative teaching. However, we should be cautious about over-reliance on technology. All in all, AI is a powerful tool that can enhance education as long as we use it wisely.",
        "key_phrases": "From my perspective, To begin with, Moreover, However, All in all, as long as",
        "category": "议论文 / 科技",
        "highlights": ["From my perspective", "To begin with", "Moreover", "However", "All in all", "as long as"],
    },
    {
        "year": 2022, "session": "12月", "title": "Environmental Protection",
        "requirements": "Write a composition on the importance of environmental protection. You should write at least 120 words.",
        "sample_essay": "It is widely acknowledged that environmental protection is one of the most pressing challenges facing humanity. To begin with, environmental damage threatens the survival of countless species, including our own. Moreover, pollution leads to enormous economic losses every year. Furthermore, as global citizens, every one of us has a responsibility to protect the planet for future generations. As far as I am concerned, I strongly recommend that we adopt greener lifestyles — using reusable bags, reducing food waste, and taking public transport more often. As the saying goes, we do not inherit the earth from our ancestors; we borrow it from our children.",
        "key_phrases": "It is widely acknowledged that, To begin with, Moreover, Furthermore, As far as I am concerned, I strongly recommend that, as the saying goes",
        "category": "议论文 / 环境",
        "highlights": ["It is widely acknowledged that", "To begin with", "Moreover", "Furthermore", "As far as I am concerned", "I strongly recommend that", "as the saying goes"],
    },
    {
        "year": 2023, "session": "6月", "title": "A Letter of Compliment",
        "requirements": "Your local library has recently renovated. Write a letter to the librarian to: 1) express your appreciation; 2) put forward some suggestions.",
        "sample_essay": "Dear Librarian, I am writing to express my heartfelt appreciation for the recent renovation of our library. The newly arranged study areas are bright, quiet and well-ventilated, which has greatly enhanced my learning experience. Moreover, the expanded digital section allows me to access a wealth of online resources. I would also like to put forward a few suggestions. First, more e-books on computer science would be a great help. Furthermore, extending the opening hours during exam season would benefit many students. Last but not least, organising book clubs would encourage more interaction among readers. I am looking forward to witnessing more positive changes. Yours sincerely, Wang Lin",
        "key_phrases": "I am writing to, express my heartfelt appreciation, Moreover, put forward, First, Furthermore, Last but not least, I am looking forward to",
        "category": "应用文 / 建议信",
        "highlights": ["I am writing to", "express my heartfelt appreciation", "Moreover", "put forward", "First", "Furthermore", "Last but not least", "I am looking forward to"],
    },
    {
        "year": 2023, "session": "12月", "title": "The Value of Patience",
        "requirements": "Write a composition on the value of patience. You should write at least 120 words.",
        "sample_essay": "There is no denying that patience is one of the most valuable virtues in life. To begin with, patience enables us to handle difficulties calmly and to think more clearly. Moreover, it helps us build stronger relationships, as conflicts can be resolved through understanding rather than anger. Furthermore, in our pursuit of career success, patience allows us to develop the deep expertise that short-term effort cannot achieve. As the saying goes, Rome was not built in a day. All in all, I strongly recommend that we cultivate patience from an early age, for it is a quality that benefits us throughout our lives.",
        "key_phrases": "There is no denying that, To begin with, Moreover, Furthermore, As the saying goes, All in all, I strongly recommend that",
        "category": "议论文 / 人生",
        "highlights": ["There is no denying that", "To begin with", "Moreover", "Furthermore", "As the saying goes", "All in all", "I strongly recommend that"],
    },
    {
        "year": 2024, "session": "6月", "title": "Chart: Daily Activities of College Students",
        "requirements": "The pie chart shows how college students spend their time on a typical weekday. Summarise the chart and comment. Write at least 120 words.",
        "sample_essay": "As is shown in the pie chart, college students today spend the majority of their weekday on academic study, which accounts for 40% of their time. Another 25% is devoted to sleeping, while the remaining time is divided among socialising, exercising, and using mobile devices. From my perspective, this distribution is largely reasonable, but some adjustments would be beneficial. To begin with, the share of physical exercise is too small, which may harm students' health in the long run. Moreover, excessive time on mobile phones tends to distract from real-life communication. I strongly recommend that universities design more outdoor activities and create phone-free zones in libraries, so that students can lead a more balanced and healthier life.",
        "key_phrases": "As is shown in, accounts for, From my perspective, To begin with, Moreover, I strongly recommend that",
        "category": "图表作文 / 生活",
        "highlights": ["As is shown in", "accounts for", "From my perspective", "To begin with", "Moreover", "I strongly recommend that"],
    },
    {
        "year": 2024, "session": "12月", "title": "Volunteer Activities",
        "requirements": "Write a composition on the importance of volunteer activities for college students. Write at least 120 words.",
        "sample_essay": "It is widely acknowledged that volunteer activities are highly beneficial for college students. To begin with, volunteering provides students with hands-on experience that cannot be gained from textbooks. Moreover, it helps them develop a sense of social responsibility and empathy. Furthermore, volunteer work is a great way to develop communication and teamwork skills, which are essential in the modern workplace. As far as I am concerned, I strongly recommend that universities set up more volunteer programmes and give students academic credit for their contributions. Only by actively serving the community can the younger generation truly grow into responsible citizens.",
        "key_phrases": "It is widely acknowledged that, To begin with, Moreover, Furthermore, As far as I am concerned, I strongly recommend that, Only by",
        "category": "议论文 / 社会",
        "highlights": ["It is widely acknowledged that", "To begin with", "Moreover", "Furthermore", "As far as I am concerned", "I strongly recommend that", "Only by"],
    },
    {
        "year": 2025, "session": "6月", "title": "A Letter of Application for a Part-time Job",
        "requirements": "You saw an ad for a part-time library assistant. Write a letter of application to include: 1) your interest; 2) your qualifications; 3) available hours.",
        "sample_essay": "Dear Sir or Madam, I am writing to apply for the position of part-time library assistant, as advertised on the school bulletin board. I am a sophomore majoring in Chinese Literature and have a deep love for books. In terms of my qualifications, I am familiar with the library's cataloguing system, having worked as a student volunteer for half a year. Moreover, I have strong organisational skills and a patient, helpful attitude. Furthermore, I am available to work from 4 to 8 p.m. on weekdays and the whole day on weekends. I am convinced that I would be an asset to your library, and I am looking forward to discussing this opportunity with you. Sincerely, Zhao Min",
        "key_phrases": "I am writing to, in terms of, Moreover, Furthermore, I am available to, I am convinced that, I am looking forward to",
        "category": "应用文 / 申请信",
        "highlights": ["I am writing to", "in terms of", "Moreover", "Furthermore", "I am available to", "I am convinced that", "I am looking forward to"],
    },
    {
        "year": 2025, "session": "12月", "title": "How to Reduce Food Waste",
        "requirements": "Write a composition on ways to reduce food waste. You should write at least 120 words.",
        "sample_essay": "It is widely acknowledged that food waste is a serious problem in modern society. To begin with, restaurants and canteens should offer smaller portions so that diners can order more flexibly. Moreover, supermarkets can discount near-expiry food rather than throwing it away. Furthermore, families should plan meals ahead and creatively use leftovers. As far as I am concerned, the most important thing is to raise public awareness of the issue. I strongly recommend that schools include food sustainability in their curricula, so that the next generation will treat every grain with the respect it deserves.",
        "key_phrases": "It is widely acknowledged that, To begin with, Moreover, Furthermore, As far as I am concerned, I strongly recommend that",
        "category": "议论文 / 社会",
        "highlights": ["It is widely acknowledged that", "To begin with", "Moreover", "Furthermore", "As far as I am concerned", "I strongly recommend that"],
    },
    {
        "year": 2026, "session": "6月 (预测)", "title": "The Importance of Sleep",
        "requirements": "Write a composition on the importance of sleep for college students. You should write at least 120 words.",
        "sample_essay": "There is no denying that adequate sleep is fundamental to college students' well-being and academic performance. To begin with, sleep plays a vital role in memory consolidation, which directly affects learning efficiency. Moreover, a good night's sleep boosts the immune system and helps prevent illness. Furthermore, sleep deprivation is closely linked to anxiety and depression, which are increasingly common among young people. As far as I am concerned, I strongly recommend that universities limit late-night activities in dormitories and educate students about healthy sleep habits. After all, a well-rested student is far more likely to achieve success than an exhausted one.",
        "key_phrases": "There is no denying that, To begin with, play a vital role in, Moreover, Furthermore, As far as I am concerned, I strongly recommend that, After all",
        "category": "议论文 / 健康",
        "highlights": ["There is no denying that", "To begin with", "play a vital role in", "Moreover", "Furthermore", "As far as I am concerned", "I strongly recommend that", "After all"],
    },
    {
        "year": 2026, "session": "12月 (预测)", "title": "Digital Payment",
        "requirements": "Write a composition on the impact of digital payment on daily life. Write at least 120 words.",
        "sample_essay": "In recent years, digital payment has revolutionised the way we handle money. From my perspective, its impact is overwhelmingly positive. To begin with, mobile payment eliminates the need to carry cash, which is both convenient and safer. Moreover, it has spurred the growth of small businesses, since even street vendors can now accept electronic transactions easily. Furthermore, digital records make it easier for users to track their spending habits. However, we should not ignore the security risks, including identity theft and fraud. All in all, digital payment is an unstoppable trend that will continue to reshape our daily lives, provided that we address the security challenges head-on.",
        "key_phrases": "From my perspective, To begin with, Moreover, Furthermore, However, All in all, provided that",
        "category": "议论文 / 科技",
        "highlights": ["From my perspective", "To begin with", "Moreover", "Furthermore", "However", "All in all", "provided that"],
    },
]


# CET-6 写作 22 篇
WRITING_CET6: list[dict] = [
    {
        "year": 2016, "session": "6月", "title": "Chart: Means of Transportation",
        "requirements": "The chart below shows the means of transportation used by residents in a city in 2010 and 2016. Summarise the chart and comment. Write at least 150 words.",
        "sample_essay": "As is vividly shown in the chart, the means of transportation used by city residents have undergone significant changes between 2010 and 2016. The proportion of people using public transport dropped from 35% to 28%, while those driving private cars rose sharply from 25% to 38%. Bicycle usage remained relatively stable at 18% to 20%, and walking decreased slightly. From my perspective, the rise of private cars is a double-edged sword. On the one hand, it reflects an improvement in living standards; on the other, it intensifies traffic congestion and air pollution. I strongly recommend that the local government invest more in public transport and create more bicycle lanes, so that the city can develop in a sustainable way.",
        "key_phrases": "undergo significant changes, From my perspective, a double-edged sword, On the one hand, on the other, I strongly recommend that",
        "category": "图表作文 / 社会",
        "highlights": ["undergo significant changes", "From my perspective", "a double-edged sword", "On the one hand", "on the other", "I strongly recommend that"],
    },
    {
        "year": 2016, "session": "12月", "title": "The Importance of Lifelong Learning",
        "requirements": "Write a composition on the importance of lifelong learning. Write at least 150 words.",
        "sample_essay": "It is widely acknowledged that lifelong learning is essential in the twenty-first century. To begin with, the rapid pace of technological change means that the skills we acquire at university may become outdated within a decade. Moreover, lifelong learning cultivates a flexible mind, which helps us adapt to new challenges and seize emerging opportunities. Furthermore, research has shown that continuous intellectual stimulation is essential to keeping our brains healthy in old age. As far as I am concerned, I strongly recommend that governments build more community libraries and online platforms to support adult learners. Only by embracing lifelong learning can individuals and societies thrive in an uncertain future.",
        "key_phrases": "It is widely acknowledged that, To begin with, Moreover, Furthermore, As far as I am concerned, I strongly recommend that, Only by",
        "category": "议论文 / 教育",
        "highlights": ["It is widely acknowledged that", "To begin with", "Moreover", "Furthermore", "As far as I am concerned", "I strongly recommend that", "Only by"],
    },
    {
        "year": 2017, "session": "6月", "title": "Chart: Use of Mobile Phones",
        "requirements": "The chart shows the average hours college students spend on mobile phones per day. Write a 150-word report.",
        "sample_essay": "As is shown in the bar chart, college students today spend an average of 5.2 hours on mobile phones every day, more than double the figure of 2010. From my perspective, this trend deserves close attention. To begin with, excessive phone usage is detrimental to physical health, especially to eyesight and posture. Moreover, the constant stream of social media notifications makes it increasingly difficult for students to concentrate on their studies. Furthermore, students who spend more time online often have weaker face-to-face communication skills. As far as I am concerned, I strongly recommend that universities run awareness campaigns about responsible phone use and that students set aside at least two hours a day for offline activities such as reading and exercise.",
        "key_phrases": "As is shown in, From my perspective, deserves close attention, To begin with, Moreover, Furthermore, As far as I am concerned, I strongly recommend that",
        "category": "图表作文 / 科技",
        "highlights": ["As is shown in", "From my perspective", "deserves close attention", "To begin with", "Moreover", "Furthermore", "As far as I am concerned", "I strongly recommend that"],
    },
    {
        "year": 2017, "session": "12月", "title": "The Importance of Innovation",
        "requirements": "Write a composition on the importance of innovation. Write at least 150 words.",
        "sample_essay": "There is no denying that innovation is the driving force behind national prosperity. To begin with, innovative products and services improve the quality of our daily life and create new markets. Moreover, innovation stimulates economic growth, which in turn provides more job opportunities. Furthermore, the spirit of innovation inspires younger generations to think boldly and tackle grand challenges. As the saying goes, a nation that ceases to innovate will gradually decline. I strongly recommend that our education system reward curiosity and risk-taking, rather than only memorising and test scores. Only in an atmosphere that celebrates innovation can our country continue to thrive in the global arena.",
        "key_phrases": "There is no denying that, To begin with, Moreover, Furthermore, As the saying goes, I strongly recommend that, Only in",
        "category": "议论文 / 创新",
        "highlights": ["There is no denying that", "To begin with", "Moreover", "Furthermore", "As the saying goes", "I strongly recommend that", "Only in"],
    },
    {
        "year": 2018, "session": "6月", "title": "Chart: Sources of Information",
        "requirements": "The pie chart shows the proportion of information sources used by people. Summarise and comment. Write at least 150 words.",
        "sample_essay": "As is clearly illustrated in the pie chart, the sources from which people obtain information have changed dramatically. While traditional media such as newspapers and television still account for 40%, the internet has rapidly risen to 45%, and social media make up 15%. From my perspective, the digital revolution has democratised information in unprecedented ways. To begin with, anyone with a smartphone can now access a wealth of knowledge at zero cost. Moreover, social media enables ordinary citizens to share their views, breaking the monopoly of mainstream media. Nevertheless, the prevalence of misinformation online is a serious concern. I strongly recommend that the government strengthen media literacy education so that citizens can distinguish reliable sources from fake news.",
        "key_phrases": "As is clearly illustrated in, From my perspective, To begin with, Moreover, Nevertheless, I strongly recommend that",
        "category": "图表作文 / 媒体",
        "highlights": ["As is clearly illustrated in", "From my perspective", "To begin with", "Moreover", "Nevertheless", "I strongly recommend that"],
    },
    {
        "year": 2018, "session": "12月", "title": "The Importance of Cross-cultural Communication",
        "requirements": "Write a composition on the importance of cross-cultural communication. Write at least 150 words.",
        "sample_essay": "It is widely acknowledged that cross-cultural communication is becoming increasingly important in the era of globalisation. To begin with, misunderstandings caused by cultural differences can lead to conflicts in international business and diplomacy. Moreover, genuine cross-cultural communication helps build trust and long-term partnerships. Furthermore, exposure to diverse cultures broadens our horizons and fosters creative thinking. As far as I am concerned, I strongly recommend that universities offer more intercultural exchange programmes and that companies train their staff in cultural sensitivity. Only when people from different backgrounds truly understand one another can the world move towards lasting peace and prosperity.",
        "key_phrases": "It is widely acknowledged that, To begin with, Moreover, Furthermore, As far as I am concerned, I strongly recommend that, Only when",
        "category": "议论文 / 文化",
        "highlights": ["It is widely acknowledged that", "To begin with", "Moreover", "Furthermore", "As far as I am concerned", "I strongly recommend that", "Only when"],
    },
    {
        "year": 2019, "session": "6月", "title": "The Influence of Pop Culture on Youth",
        "requirements": "Write a composition on the influence of pop culture on young people. Write at least 150 words.",
        "sample_essay": "It goes without saying that pop culture exerts a profound influence on today's youth. On the positive side, pop culture provides young people with rich sources of entertainment and inspiration, broadening their cultural horizons. Moreover, social media platforms allow them to express themselves and connect with like-minded peers around the world. On the negative side, however, the pursuit of celebrity lifestyles may distort young people's values, encouraging them to seek fame rather than substance. Furthermore, excessive exposure to social media can lead to anxiety and addiction. I strongly recommend that schools teach media literacy so that young people can enjoy pop culture while maintaining a clear sense of self.",
        "key_phrases": "It goes without saying that, On the positive side, On the negative side, Moreover, Furthermore, I strongly recommend that",
        "category": "议论文 / 文化",
        "highlights": ["It goes without saying that", "On the positive side", "On the negative side", "Moreover", "Furthermore", "I strongly recommend that"],
    },
    {
        "year": 2019, "session": "12月", "title": "Chart: Spending on Books",
        "requirements": "The chart shows the amount of money college students spend on books per year. Write a 150-word report.",
        "sample_essay": "As is vividly depicted in the chart, college students' average annual spending on books has fluctuated considerably over the past five years. While spending on paper books has dropped from 350 yuan to 220 yuan, the figure for e-books and audiobooks has climbed from 50 to 280 yuan, surpassing the former in 2019. From my perspective, this shift reflects two major changes. To begin with, digital reading offers unbeatable convenience, allowing students to carry a whole library in their pocket. Moreover, many universities now provide free access to large e-book databases, which has further accelerated the trend. Nevertheless, I would argue that paper books still have unique value, and that a balanced reading diet is the healthiest approach.",
        "key_phrases": "As is vividly depicted in, From my perspective, To begin with, Moreover, Nevertheless, I would argue that",
        "category": "图表作文 / 教育",
        "highlights": ["As is vividly depicted in", "From my perspective", "To begin with", "Moreover", "Nevertheless", "I would argue that"],
    },
    {
        "year": 2020, "session": "7月", "title": "The Importance of Mental Health",
        "requirements": "Write a composition on the importance of mental health. Write at least 150 words.",
        "sample_essay": "It is widely acknowledged that mental health is just as important as physical health, yet it is often overlooked. To begin with, good mental health is the foundation of productivity and creativity, which are essential for both study and work. Moreover, untreated mental issues can lead to severe social problems, including depression, anxiety and even suicide. Furthermore, the stigma surrounding mental illness in many cultures prevents people from seeking timely help. As far as I am concerned, I strongly recommend that schools set up accessible counselling services and that employers create a more supportive work environment. Only when mental health is taken as seriously as physical health can individuals and societies flourish.",
        "key_phrases": "It is widely acknowledged that, To begin with, Moreover, Furthermore, As far as I am concerned, I strongly recommend that, Only when",
        "category": "议论文 / 健康",
        "highlights": ["It is widely acknowledged that", "To begin with", "Moreover", "Furthermore", "As far as I am concerned", "I strongly recommend that", "Only when"],
    },
    {
        "year": 2020, "session": "9月", "title": "Chart: Online Education vs. Offline",
        "requirements": "The chart shows the percentage of students preferring online vs. offline education. Write a 150-word analysis.",
        "sample_essay": "As is shown in the chart, student preferences for online and offline education have shifted markedly over the past two years. In 2018, only 30% of students favoured online classes, while 70% preferred traditional classrooms. By 2020, the online share had risen to 55%, almost equal to that of offline. From my perspective, the pandemic was a key driver of this change, but the underlying trend was already visible. To begin with, online education provides flexibility that suits working adults and remote learners. Moreover, technological advances have made virtual classrooms far more engaging. Nevertheless, I would argue that offline education remains irreplaceable for subjects requiring hands-on practice, such as laboratory sciences.",
        "key_phrases": "As is shown in, From my perspective, To begin with, Moreover, Nevertheless, I would argue that",
        "category": "图表作文 / 教育",
        "highlights": ["As is shown in", "From my perspective", "To begin with", "Moreover", "Nevertheless", "I would argue that"],
    },
    {
        "year": 2021, "session": "6月", "title": "The Value of Reading Classics",
        "requirements": "Write a composition on the value of reading classics. Write at least 150 words.",
        "sample_essay": "It is widely acknowledged that reading classics is a rewarding habit that yields long-term benefits. To begin with, classics embody the deepest thoughts of human civilization, offering readers wisdom that stands the test of time. Moreover, exposure to great literature enriches our language, sharpens our critical thinking and nurtures our aesthetic sense. Furthermore, the dialogue between past and present that classics enable helps us understand our own identities and cultures. As far as I am concerned, I strongly recommend that young people set aside half an hour a day to read classics, no matter how busy they are. After all, the more we read, the more we understand life.",
        "key_phrases": "It is widely acknowledged that, To begin with, Moreover, Furthermore, As far as I am concerned, I strongly recommend that, the more... the more",
        "category": "议论文 / 文化",
        "highlights": ["It is widely acknowledged that", "To begin with", "Moreover", "Furthermore", "As far as I am concerned", "I strongly recommend that", "the more... the more"],
    },
    {
        "year": 2021, "session": "12月", "title": "The Impact of Social Media on Interpersonal Relationships",
        "requirements": "Write a composition on the impact of social media on interpersonal relationships. Write at least 150 words.",
        "sample_essay": "It goes without saying that social media has transformed the way we maintain relationships. On the positive side, it enables us to stay in touch with friends and family across the globe at virtually no cost. Moreover, online communities bring together people who share rare interests, helping them find support and friendship. On the negative side, however, the superficial nature of online interactions can erode the depth of real relationships. Furthermore, social media often fuels jealousy and comparison, putting a strain on offline friendships. I strongly recommend that we treat social media as a tool to enhance — not replace — face-to-face relationships. Only by striking a healthy balance can we enjoy the benefits of technology without losing human warmth.",
        "key_phrases": "It goes without saying that, On the positive side, On the negative side, Moreover, Furthermore, I strongly recommend that, Only by",
        "category": "议论文 / 社交",
        "highlights": ["It goes without saying that", "On the positive side", "On the negative side", "Moreover", "Furthermore", "I strongly recommend that", "Only by"],
    },
    {
        "year": 2022, "session": "6月", "title": "Chart: Carbon Emissions by Sector",
        "requirements": "The chart shows carbon emissions by sector in a country. Summarise and comment. Write at least 150 words.",
        "sample_essay": "As is vividly depicted in the pie chart, carbon emissions are distributed unevenly across sectors in this country. The energy sector accounts for the largest share at 45%, followed by industry at 30%, transportation at 15%, and other sectors at 10%. From my perspective, this distribution highlights the urgent need to restructure the energy system. To begin with, replacing coal-fired power plants with renewable sources is the single most effective step. Moreover, upgrading public transport and promoting electric vehicles can significantly cut transportation emissions. Furthermore, every citizen can play a role by adopting low-carbon lifestyles. I strongly recommend that the government set ambitious yet realistic emission targets and provide incentives for green innovation.",
        "key_phrases": "As is vividly depicted in, accounts for, From my perspective, To begin with, Moreover, Furthermore, I strongly recommend that",
        "category": "图表作文 / 环境",
        "highlights": ["As is vividly depicted in", "accounts for", "From my perspective", "To begin with", "Moreover", "Furthermore", "I strongly recommend that"],
    },
    {
        "year": 2022, "session": "12月", "title": "A Letter Applying for a Scholarship",
        "requirements": "Write a letter to apply for an academic scholarship. Include: 1) your academic record; 2) your financial need; 3) your future plan.",
        "sample_essay": "Dear Sir or Madam, I am writing to apply for the Academic Excellence Scholarship offered by your university. In terms of my academic record, I have maintained a GPA of 3.8, ranking among the top 5% in my department. Moreover, I have won the National Scholarship for two consecutive years and published a paper in a core journal. As for my financial situation, my father is the sole breadwinner of our family of four, and the tuition fees pose a heavy burden. With the scholarship, I would be able to focus more on my research on sustainable urban development, which I plan to pursue as a master's student. I would be deeply grateful for your consideration. Yours sincerely, Liu Yang",
        "key_phrases": "I am writing to, in terms of, Moreover, As for, focus on, I would be deeply grateful",
        "category": "应用文 / 申请信",
        "highlights": ["I am writing to", "in terms of", "Moreover", "As for", "focus on", "I would be deeply grateful"],
    },
    {
        "year": 2023, "session": "6月", "title": "The Importance of Cultural Heritage Preservation",
        "requirements": "Write a composition on the importance of cultural heritage preservation. Write at least 150 words.",
        "sample_essay": "It is widely acknowledged that cultural heritage is a priceless treasure that connects us to our ancestors. To begin with, ancient buildings, rituals and crafts embody the unique wisdom and aesthetic tastes of past generations. Moreover, cultural heritage is a powerful driver of tourism, generating significant economic benefits. Furthermore, in a rapidly globalising world, preserving our heritage strengthens national identity and fosters cultural diversity. Nevertheless, urbanisation and commercialisation are putting many heritage sites at risk. I strongly recommend that governments allocate more funding to conservation efforts and that the younger generation be actively involved in passing traditions down.",
        "key_phrases": "It is widely acknowledged that, To begin with, Moreover, Furthermore, Nevertheless, I strongly recommend that",
        "category": "议论文 / 文化",
        "highlights": ["It is widely acknowledged that", "To begin with", "Moreover", "Furthermore", "Nevertheless", "I strongly recommend that"],
    },
    {
        "year": 2023, "session": "12月", "title": "Chart: Time Spent on Social Media",
        "requirements": "The chart shows daily time spent on social media by age group. Write a 150-word analysis.",
        "sample_essay": "As is shown in the chart, the daily time spent on social media varies dramatically across age groups. People aged 18-25 spend an astonishing 4.5 hours a day on social platforms, while the figure for those aged 46-60 is only 1.2 hours. From my perspective, this generational gap deserves close attention. To begin with, excessive time on social media can harm young people's physical and mental health, including eye strain, sleep deprivation and anxiety. Moreover, the algorithms of social platforms often create echo chambers, reinforcing biases and polarisation. As far as I am concerned, I strongly recommend that young people set strict time limits and engage in more offline activities such as sports and reading. A balanced lifestyle is the key to well-being.",
        "key_phrases": "As is shown in, From my perspective, deserves close attention, To begin with, Moreover, As far as I am concerned, I strongly recommend that",
        "category": "图表作文 / 社交",
        "highlights": ["As is shown in", "From my perspective", "deserves close attention", "To begin with", "Moreover", "As far as I am concerned", "I strongly recommend that"],
    },
    {
        "year": 2024, "session": "6月", "title": "The Importance of Critical Thinking in Education",
        "requirements": "Write a composition on the importance of critical thinking in education. Write at least 150 words.",
        "sample_essay": "It is widely acknowledged that critical thinking is the cornerstone of quality education. To begin with, critical thinking empowers students to analyse problems independently rather than accept information at face value. Moreover, in an age of information overload, the ability to discern reliable sources from misinformation is more important than ever. Furthermore, critical thinking fosters creativity, which is essential for innovation and entrepreneurship. As far as I am concerned, I strongly recommend that schools reduce rote learning and introduce more discussion-based classes. After all, education is not just about transferring knowledge but also about cultivating minds that can change the world.",
        "key_phrases": "It is widely acknowledged that, To begin with, Moreover, Furthermore, As far as I am concerned, I strongly recommend that, After all",
        "category": "议论文 / 教育",
        "highlights": ["It is widely acknowledged that", "To begin with", "Moreover", "Furthermore", "As far as I am concerned", "I strongly recommend that", "After all"],
    },
    {
        "year": 2024, "session": "12月", "title": "The Impact of AI on Employment",
        "requirements": "Write a composition on the impact of AI on employment. Write at least 150 words.",
        "sample_essay": "It is widely acknowledged that artificial intelligence is reshaping the global labour market in profound ways. To begin with, automation is gradually replacing routine jobs in manufacturing and clerical work. Moreover, AI is creating new occupations, such as prompt engineers and AI ethicists, that did not exist a decade ago. Furthermore, the rise of AI demands that workers continuously upgrade their skills, making lifelong learning a necessity rather than a luxury. Nevertheless, this transition also brings serious challenges, including rising inequality and job insecurity. As far as I am concerned, I strongly recommend that governments invest heavily in reskilling programmes and that individuals embrace change with a positive mindset.",
        "key_phrases": "It is widely acknowledged that, To begin with, Moreover, Furthermore, Nevertheless, As far as I am concerned, I strongly recommend that",
        "category": "议论文 / 科技",
        "highlights": ["It is widely acknowledged that", "To begin with", "Moreover", "Furthermore", "Nevertheless", "As far as I am concerned", "I strongly recommend that"],
    },
    {
        "year": 2025, "session": "6月", "title": "Chart: Reasons for Studying Abroad",
        "requirements": "The chart shows the reasons why Chinese students choose to study abroad. Write a 150-word report.",
        "sample_essay": "As is clearly illustrated in the chart, Chinese students choose to study abroad for a variety of reasons. Better educational resources top the list at 40%, followed by broader career prospects at 25%, exposure to different cultures at 20%, and personal growth at 15%. From my perspective, these reasons reflect both rational and aspirational motivations. To begin with, the world-class universities abroad offer cutting-edge research facilities that attract ambitious students. Moreover, studying in a foreign country helps young people develop independence and cross-cultural skills. However, the rising cost of overseas education is a concern. I strongly recommend that students weigh their goals carefully and consider scholarship opportunities before making the decision.",
        "key_phrases": "As is clearly illustrated in, From my perspective, To begin with, Moreover, However, I strongly recommend that",
        "category": "图表作文 / 教育",
        "highlights": ["As is clearly illustrated in", "From my perspective", "To begin with", "Moreover", "However", "I strongly recommend that"],
    },
    {
        "year": 2025, "session": "12月", "title": "How to Be a Good Team Player",
        "requirements": "Write a composition on the qualities of a good team player. Write at least 150 words.",
        "sample_essay": "It is widely acknowledged that the ability to work well in a team is a crucial skill in the modern workplace. To begin with, a good team player actively listens to others and respects diverse viewpoints, even when they differ from his own. Moreover, effective communication and a willingness to compromise are essential for resolving conflicts. Furthermore, taking responsibility for one's own work while supporting teammates is the hallmark of a reliable team player. As far as I am concerned, I strongly recommend that universities create more group projects to give students hands-on experience in collaboration. After all, no matter how talented an individual is, the synergy of a strong team can achieve far more.",
        "key_phrases": "It is widely acknowledged that, To begin with, Moreover, Furthermore, As far as I am concerned, I strongly recommend that, After all",
        "category": "议论文 / 职场",
        "highlights": ["It is widely acknowledged that", "To begin with", "Moreover", "Furthermore", "As far as I am concerned", "I strongly recommend that", "After all"],
    },
    {
        "year": 2026, "session": "6月 (预测)", "title": "The Role of AI in Education",
        "requirements": "Write a composition on the role of AI in education. Write at least 150 words.",
        "sample_essay": "There is no denying that artificial intelligence is revolutionising education worldwide. To begin with, AI-powered tutoring systems can identify a student's weak areas and tailor exercises accordingly, making personalised learning scalable. Moreover, AI tools can automate routine tasks such as grading, freeing teachers to focus on inspiring creativity and critical thinking. Furthermore, intelligent translation and speech technologies are breaking down language barriers, allowing students worldwide to access world-class resources. As far as I am concerned, however, AI can never replace the warmth and wisdom of a great teacher. I strongly recommend that we use AI as an assistant, not a substitute, in the classroom.",
        "key_phrases": "There is no denying that, To begin with, Moreover, Furthermore, As far as I am concerned, I strongly recommend that",
        "category": "议论文 / 科技",
        "highlights": ["There is no denying that", "To begin with", "Moreover", "Furthermore", "As far as I am concerned", "I strongly recommend that"],
    },
    {
        "year": 2026, "session": "12月 (预测)", "title": "The Importance of Soft Skills",
        "requirements": "Write a composition on the importance of soft skills. Write at least 150 words.",
        "sample_essay": "It is widely acknowledged that in addition to technical expertise, soft skills such as communication, teamwork and emotional intelligence play a vital role in career success. To begin with, strong communication skills help individuals express their ideas clearly, which is essential in any collaborative environment. Moreover, empathy enables people to understand colleagues' feelings, fostering a positive workplace culture. Furthermore, adaptability and a growth mindset allow professionals to thrive amid rapid change. As far as I am concerned, I strongly recommend that universities complement academic courses with soft-skill training, such as public-speaking clubs and leadership programmes. After all, the most successful professionals are not just the smartest but also the most well-rounded.",
        "key_phrases": "It is widely acknowledged that, play a vital role in, To begin with, Moreover, Furthermore, As far as I am concerned, I strongly recommend that, After all",
        "category": "议论文 / 职场",
        "highlights": ["It is widely acknowledged that", "play a vital role in", "To begin with", "Moreover", "Furthermore", "As far as I am concerned", "I strongly recommend that", "After all"],
    },
]